// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_forms_demo2::aptos_forms_demo2_start_page_aggregate {
    use aptos_forms_demo2::aptos_forms_demo2_start_page;
    use aptos_forms_demo2::aptos_forms_demo2_start_page_submit_logic;
    use aptos_forms_demo2::aptos_forms_demo2_start_page_update_logic;
    use std::string::String;

    public entry fun submit(
        account: &signer,
        fr_jq19: String,
        fr_3c5z: u128,
        fr_d1h2: String,
        fr_7gbq: vector<String>,
        fr_h4t4: String,
        fr_5jh4: vector<String>,
        fr_bzpt: String,
        fr_1kci: bool,
        fr_9i6h: bool,
        fr_jyqo: u128,
        fr_3eds: u128,
        fr_e62y: vector<u16>,
        fr_vki: vector<u16>,
        fr_6znw: vector<u8>,
        fr_4ncu: vector<u8>,
        fr_1cbi: String,
        fr_18bq: String,
        fr_lb63: String,
        fr_iyqp: String,
        fr_hfdf: String,
    ) {
        let aptos_forms_demo2_start_page_submitted = aptos_forms_demo2_start_page_submit_logic::verify(
            account,
            fr_jq19,
            fr_3c5z,
            fr_d1h2,
            fr_7gbq,
            fr_h4t4,
            fr_5jh4,
            fr_bzpt,
            fr_1kci,
            fr_9i6h,
            fr_jyqo,
            fr_3eds,
            xrender_form_utils::date::value_of(fr_e62y),
            xrender_form_utils::date_range::value_of(fr_vki),
            xrender_form_utils::time::value_of(fr_6znw),
            xrender_form_utils::time_range::value_of(fr_4ncu),
            fr_1cbi,
            fr_18bq,
            fr_lb63,
            fr_iyqp,
            fr_hfdf,
        );
        let aptos_forms_demo2_start_page = aptos_forms_demo2_start_page_submit_logic::mutate(
            account,
            &aptos_forms_demo2_start_page_submitted,
        );
        aptos_forms_demo2_start_page::add_aptos_forms_demo2_start_page(aptos_forms_demo2_start_page);
        aptos_forms_demo2_start_page::emit_aptos_forms_demo2_start_page_submitted(aptos_forms_demo2_start_page_submitted);
    }

    public entry fun update(
        account: &signer,
        signer_address: address,
        fr_jq19: String,
        fr_3c5z: u128,
        fr_d1h2: String,
        fr_7gbq: vector<String>,
        fr_h4t4: String,
        fr_5jh4: vector<String>,
        fr_bzpt: String,
        fr_1kci: bool,
        fr_9i6h: bool,
        fr_jyqo: u128,
        fr_3eds: u128,
        fr_e62y: vector<u16>,
        fr_vki: vector<u16>,
        fr_6znw: vector<u8>,
        fr_4ncu: vector<u8>,
        fr_1cbi: String,
        fr_18bq: String,
        fr_lb63: String,
        fr_iyqp: String,
        fr_hfdf: String,
    ) {
        let aptos_forms_demo2_start_page = aptos_forms_demo2_start_page::remove_aptos_forms_demo2_start_page(signer_address);
        let aptos_forms_demo2_start_page_updated = aptos_forms_demo2_start_page_update_logic::verify(
            account,
            fr_jq19,
            fr_3c5z,
            fr_d1h2,
            fr_7gbq,
            fr_h4t4,
            fr_5jh4,
            fr_bzpt,
            fr_1kci,
            fr_9i6h,
            fr_jyqo,
            fr_3eds,
            xrender_form_utils::date::value_of(fr_e62y),
            xrender_form_utils::date_range::value_of(fr_vki),
            xrender_form_utils::time::value_of(fr_6znw),
            xrender_form_utils::time_range::value_of(fr_4ncu),
            fr_1cbi,
            fr_18bq,
            fr_lb63,
            fr_iyqp,
            fr_hfdf,
            &aptos_forms_demo2_start_page,
        );
        let updated_aptos_forms_demo2_start_page = aptos_forms_demo2_start_page_update_logic::mutate(
            account,
            &aptos_forms_demo2_start_page_updated,
            aptos_forms_demo2_start_page,
        );
        aptos_forms_demo2_start_page::update_version_and_add(updated_aptos_forms_demo2_start_page);
        aptos_forms_demo2_start_page::emit_aptos_forms_demo2_start_page_updated(aptos_forms_demo2_start_page_updated);
    }

}
