FROM ubuntu:22.04

RUN apt-get update && \
apt-get install -y unzip && \
apt-get install -y git && \
rm -rf /var/lib/apt/lists/*

WORKDIR /opt/aptos

ADD https://github.com/aptos-labs/aptos-core/releases/download/aptos-cli-v3.4.1/aptos-cli-3.4.1-Ubuntu-22.04-x86_64.zip /opt/aptos/

RUN unzip aptos-cli-3.4.1-Ubuntu-22.04-x86_64.zip && \
rm aptos-cli-3.4.1-Ubuntu-22.04-x86_64.zip

RUN chmod +x aptos

ENTRYPOINT ["/opt/aptos/aptos"]