FROM ubuntu:22.04

RUN apt-get update && \
apt-get install -y unzip git wget software-properties-common && \
add-apt-repository ppa:openjdk-r/ppa && \
apt-get update && \
apt-get install -y openjdk-21-jdk && \
rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:${PATH}"

WORKDIR /opt/dddappp
RUN git clone https://github.com/dddappp/XRender-Form-Utils.git

WORKDIR /opt/aptos

ADD https://github.com/aptos-labs/aptos-core/releases/download/aptos-cli-v4.0.0/aptos-cli-4.0.0-Ubuntu-22.04-x86_64.zip /opt/aptos/

RUN unzip aptos-cli-4.0.0-Ubuntu-22.04-x86_64.zip && \
rm aptos-cli-4.0.0-Ubuntu-22.04-x86_64.zip

RUN chmod +x aptos

RUN ./aptos move compile --save-metadata --package-dir /opt/dddappp/XRender-Form-Utils/aptos-move --named-addresses xrender_form_utils=0x71df3ab1b6cf015aa5870a8a6e8ee0951c54e8d7d79bb59fa3b737c3a38fb93b --skip-fetch-latest-git-deps

ENTRYPOINT ["/opt/aptos/aptos"]
